 scrape_configs:
   - job_name: 'jmeter'
     scrape_interval: 5s
     static_configs:
        - targets: ['jenkins:9280']
   - job_name: 'springboot-app'
     metrics_path: '/actuator/prometheus'
     static_configs:
        - targets: ['192.168.1.241:8080']