version: "3.8"
services:
  postgres:
    image: "postgres:16.1"
    container_name: "postgres"
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test_db
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d test_db"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

volumes:
  db:
    driver: local