spring:
  profiles:
    active: jooq
  application:
    name: city-management
  datasource:
    url: ${POSTGRESQL_DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${POSTGRESQL_DB_USERNAME:postgres}
    password: ${POSTGRESQL_DB_PASSWORD:postgres}
    driverClassName: ${POSTGRESQL_DB_DRIVER:org.postgresql.Driver}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: ${LIQUIBASE_MODE:true}
    change-log: classpath:db/changelog/master.yml